# Pipeline Documentation:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

strategy:
  matrix:
    vs2017:
      imageName: 'vs2017-win2016'
    vs2019:
      imageName: 'windows-latest'

trigger:
- master

pool:
  vmImage: $(imageName)

variables:
  solution: 'ConsoleApp1.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Build /verbosity:diagnostic'
